name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t stephengrider/docker-react -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true stephengrider/docker-react npm run test
